# Generated by Django 4.0.3 on 2023-03-08 05:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sales_rest', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='automobilevo',
            old_name='is_sold',
            new_name='sold',
        ),
    ]
