# Generated by Django 4.0.3 on 2023-03-07 20:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service_rest', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointment',
            name='purchased_from_inventory',
        ),
        migrations.RemoveField(
            model_name='automobilevo',
            name='inventory_vehicle',
        ),
    ]
