# Generated by Django 4.0.3 on 2023-03-09 21:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service_rest', '0003_appointment_is_vip'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointment',
            name='is_vip',
        ),
    ]
